[package]
name = "vid2bin"
version = "0.1.0"
authors = ["vlad <vladov3000@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gif = "0.11.1"
termion = "1.5.5"
clap = "3.0.0-beta.2"
